apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  installationId: {{ .Values.global.installationId }}
  installationKey: {{ .Values.global.installationKey }}
  app-id.json: |
    {
      "trustedFacets": [
        {
          "version": {
          "major": 1,
          "minor": 0
        },
          "ids": [
            "https://{{ .Values.global.domain }}",
            "ios:bundle-id:com.8bit.bitwarden",
            "android:apk-key-hash:dUGFzUzf3lmHSLBDBIv+WaFyZMI"
          ]
        }
      ]
    }
    