apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-secrets
type: Opaque
data:
  sa_password: {{ .Values.db.password | b64enc | quote }}
  {{ $dsn := print "Data Source=tcp:" .Values.db.host "," .Values.db.port ";Initial Catalog=vault;Persist Security Info=False;User ID=" .Values.db.username ";Password=" .Values.db.password ";MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True" }}
  mssql_dsn: {{ $dsn | b64enc }}
  internal_identity_key: {{ .Values.secrets.internalIdentityKey | b64enc | quote }}
  duo_akey: {{ .Values.secrets.duoAKey | b64enc }}
  certificate_password: {{ .Values.secrets.certificate_password | b64enc | quote }}
  smtp_passwd: {{ .Values.global.env.mail.globalSettings__mail__smtp__password | b64enc | quote }}
  oidc_identity_client_key:  {{ .Values.global.env.oidc.globalSettings__oidcIdentityClientKey | b64enc | quote }}
  yubico_key: {{ .Values.global.env.yubico.globalSettings__yubico__key | b64enc | quote }}